// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ActivitiesDocumentDataSlicesSlice =
  | ActivitiesBannerSlice
  | ActivityContainerSlice;

/**
 * Content for Activities documents
 */
interface ActivitiesDocumentData {
  /**
   * Slice Zone field in *Activities*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ActivitiesDocumentDataSlicesSlice> /**
   * Meta Title field in *Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: activities.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Activities*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: activities.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Activities*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Activities document from Prismic
 *
 * - **API ID**: `activities`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ActivitiesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ActivitiesDocumentData>,
    "activities",
    Lang
  >;

type CoursesDocumentDataSlicesSlice = CtaSlice | CourseCardsSlice | HeaderSlice;

/**
 * Content for Courses documents
 */
interface CoursesDocumentData {
  /**
   * Slice Zone field in *Courses*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CoursesDocumentDataSlicesSlice> /**
   * Meta Title field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: courses.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Courses*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: courses.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Courses*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Courses document from Prismic
 *
 * - **API ID**: `courses`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CoursesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CoursesDocumentData>,
    "courses",
    Lang
  >;

/**
 * Content for Event Card documents
 */
interface EventCardDocumentData {
  /**
   * Event Badge field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_badge
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_badge: prismic.RichTextField;

  /**
   * Event Duration field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_duration
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_duration: prismic.RichTextField;

  /**
   * Event Title field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_title: prismic.RichTextField;

  /**
   * Event Body field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_body
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_body: prismic.RichTextField;

  /**
   * Event Dates field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_dates
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_dates: prismic.RichTextField;

  /**
   * Event Location field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_location: prismic.RichTextField;

  /**
   * Event Fees Title field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_fees_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_fees_title: prismic.RichTextField;

  /**
   * Event Fees Attendance field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_fees_attendance
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_fees_attendance: prismic.RichTextField;

  /**
   * Event Fees Workbook field in *Event Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_fees_workbook
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_fees_workbook: prismic.RichTextField;

  /**
   * Event Signup Link field in *Event Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: event_card.event_signup_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event_signup_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Event Card document from Prismic
 *
 * - **API ID**: `event_card`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventCardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<EventCardDocumentData>,
    "event_card",
    Lang
  >;

type EventsDocumentDataSlicesSlice = EventsBannerSlice;

/**
 * Content for events documents
 */
interface EventsDocumentData {
  /**
   * Slice Zone field in *events*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: events.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<EventsDocumentDataSlicesSlice> /**
   * Meta Title field in *events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: events.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *events*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: events.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: events.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * events document from Prismic
 *
 * - **API ID**: `events`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<EventsDocumentData>, "events", Lang>;

type HomepageDocumentDataSlicesSlice =
  | ContactSlice
  | TestimonialsSlice
  | PartnersAndClientsSlice
  | TeamSlice
  | ActivitiesSlice
  | EventsSlice
  | BlogsSlice
  | CoursesSlice
  | AboutSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Settings → NavIcons*
 */
export interface SettingsDocumentDataNaviconsItem {
  /**
   * social icons field in *Settings → NavIcons*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navicons[].social_icons
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  social_icons: prismic.SelectField<
    "LinkedIn" | "Instagram" | "Twitter" | "Facebook"
  >;

  /**
   * IconLink field in *Settings → NavIcons*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navicons[].iconlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  iconlink: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Fallback OG Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.fallback_og_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fallback_og_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * NavIcons field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navicons[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navicons: prismic.GroupField<Simplify<SettingsDocumentDataNaviconsItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ActivitiesDocument
  | CoursesDocument
  | EventCardDocument
  | EventsDocument
  | HomepageDocument
  | SettingsDocument;

/**
 * Primary content in *About → Default → Primary*
 */
export interface AboutSliceDefaultPrimary {
  /**
   * Heading field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Mission Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.mission_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mission_image: prismic.ImageField<never>;

  /**
   * Mission Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.mission_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mission_title: prismic.RichTextField;

  /**
   * Mission Body field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.mission_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  mission_body: prismic.RichTextField;

  /**
   * Vision Image field in *About → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.vision_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  vision_image: prismic.ImageField<never>;

  /**
   * Vision Title field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.vision_title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  vision_title: prismic.RichTextField;

  /**
   * Vision Body field in *About → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.default.primary.vision_body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  vision_body: prismic.RichTextField;
}

/**
 * Default variation for About Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *About*
 */
type AboutSliceVariation = AboutSliceDefault;

/**
 * About Shared Slice
 *
 * - **API ID**: `about`
 * - **Description**: About
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSlice = prismic.SharedSlice<"about", AboutSliceVariation>;

/**
 * Item in *Activities → Default → Primary → Activities Card*
 */
export interface ActivitiesSliceDefaultPrimaryActivitiesCardItem {
  /**
   * Image field in *Activities → Default → Primary → Activities Card*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.activities_card[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Activities → Default → Primary → Activities Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.activities_card[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Activities → Default → Primary → Activities Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.activities_card[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Activities → Default → Primary → Activities Card*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.activities_card[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Activities → Default → Primary*
 */
export interface ActivitiesSliceDefaultPrimary {
  /**
   * Heading field in *Activities → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Activities Card field in *Activities → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: activities.default.primary.activities_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  activities_card: prismic.GroupField<
    Simplify<ActivitiesSliceDefaultPrimaryActivitiesCardItem>
  >;
}

/**
 * Default variation for Activities Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActivitiesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Activities*
 */
type ActivitiesSliceVariation = ActivitiesSliceDefault;

/**
 * Activities Shared Slice
 *
 * - **API ID**: `activities`
 * - **Description**: Activities
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesSlice = prismic.SharedSlice<
  "activities",
  ActivitiesSliceVariation
>;

/**
 * Primary content in *ActivitiesBanner → Default → Primary*
 */
export interface ActivitiesBannerSliceDefaultPrimary {
  /**
   * Image field in *ActivitiesBanner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ActivitiesBanner → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for ActivitiesBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActivitiesBannerSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *ActivitiesBanner → Training → Primary*
 */
export interface ActivitiesBannerSliceTrainingPrimary {
  /**
   * Image field in *ActivitiesBanner → Training → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.training.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ActivitiesBanner → Training → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.training.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Training variation for ActivitiesBanner Slice
 *
 * - **API ID**: `training`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesBannerSliceTraining = prismic.SharedSliceVariation<
  "training",
  Simplify<ActivitiesBannerSliceTrainingPrimary>,
  never
>;

/**
 * Primary content in *ActivitiesBanner → Online → Primary*
 */
export interface ActivitiesBannerSliceOnlinePrimary {
  /**
   * Image field in *ActivitiesBanner → Online → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.online.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *ActivitiesBanner → Online → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activities_banner.online.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Online variation for ActivitiesBanner Slice
 *
 * - **API ID**: `online`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesBannerSliceOnline = prismic.SharedSliceVariation<
  "online",
  Simplify<ActivitiesBannerSliceOnlinePrimary>,
  never
>;

/**
 * Slice variation for *ActivitiesBanner*
 */
type ActivitiesBannerSliceVariation =
  | ActivitiesBannerSliceDefault
  | ActivitiesBannerSliceTraining
  | ActivitiesBannerSliceOnline;

/**
 * ActivitiesBanner Shared Slice
 *
 * - **API ID**: `activities_banner`
 * - **Description**: ActivitiesBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivitiesBannerSlice = prismic.SharedSlice<
  "activities_banner",
  ActivitiesBannerSliceVariation
>;

/**
 * Item in *ActivityContainer → Default → Primary → Gallery*
 */
export interface ActivityContainerSliceDefaultPrimaryGalleryItem {
  /**
   * Gallery Image field in *ActivityContainer → Default → Primary → Gallery*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.gallery[].gallery_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  gallery_image: prismic.ImageField<never>;
}

/**
 * Primary content in *ActivityContainer → Default → Primary*
 */
export interface ActivityContainerSliceDefaultPrimary {
  /**
   * Title field in *ActivityContainer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Trainer field in *ActivityContainer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.trainer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  trainer: prismic.RichTextField;

  /**
   * Description field in *ActivityContainer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Image field in *ActivityContainer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Gallery field in *ActivityContainer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: activity_container.default.primary.gallery[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  gallery: prismic.GroupField<
    Simplify<ActivityContainerSliceDefaultPrimaryGalleryItem>
  >;
}

/**
 * Default variation for ActivityContainer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivityContainerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ActivityContainerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ActivityContainer*
 */
type ActivityContainerSliceVariation = ActivityContainerSliceDefault;

/**
 * ActivityContainer Shared Slice
 *
 * - **API ID**: `activity_container`
 * - **Description**: ActivityContainer
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ActivityContainerSlice = prismic.SharedSlice<
  "activity_container",
  ActivityContainerSliceVariation
>;

/**
 * Item in *Blogs → Default → Primary → Blog Cards*
 */
export interface BlogsSliceDefaultPrimaryBlogCardsItem {
  /**
   * Title field in *Blogs → Default → Primary → Blog Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.blog_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Blogs → Default → Primary → Blog Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.blog_cards[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Blogs → Default → Primary → Blog Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.blog_cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Image field in *Blogs → Default → Primary → Blog Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.blog_cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Blogs → Default → Primary*
 */
export interface BlogsSliceDefaultPrimary {
  /**
   * Heading field in *Blogs → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Blog Cards field in *Blogs → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: blogs.default.primary.blog_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  blog_cards: prismic.GroupField<
    Simplify<BlogsSliceDefaultPrimaryBlogCardsItem>
  >;
}

/**
 * Default variation for Blogs Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BlogsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Blogs*
 */
type BlogsSliceVariation = BlogsSliceDefault;

/**
 * Blogs Shared Slice
 *
 * - **API ID**: `blogs`
 * - **Description**: Blogs
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogsSlice = prismic.SharedSlice<"blogs", BlogsSliceVariation>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Heading field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Item in *CourseCards → Default → Primary → Course Cards*
 */
export interface CourseCardsSliceDefaultPrimaryCourseCardsItem {
  /**
   * Title field in *CourseCards → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_cards.default.primary.course_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Code field in *CourseCards → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_cards.default.primary.course_cards[].code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  code: prismic.RichTextField;

  /**
   * Description field in *CourseCards → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_cards.default.primary.course_cards[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Duration field in *CourseCards → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: course_cards.default.primary.course_cards[].duration
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  duration: prismic.RichTextField;
}

/**
 * Primary content in *CourseCards → Default → Primary*
 */
export interface CourseCardsSliceDefaultPrimary {
  /**
   * Course Cards field in *CourseCards → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: course_cards.default.primary.course_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  course_cards: prismic.GroupField<
    Simplify<CourseCardsSliceDefaultPrimaryCourseCardsItem>
  >;
}

/**
 * Default variation for CourseCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CourseCardsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CourseCards*
 */
type CourseCardsSliceVariation = CourseCardsSliceDefault;

/**
 * CourseCards Shared Slice
 *
 * - **API ID**: `course_cards`
 * - **Description**: CourseCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CourseCardsSlice = prismic.SharedSlice<
  "course_cards",
  CourseCardsSliceVariation
>;

/**
 * Item in *Courses → Default → Primary → Course Cards*
 */
export interface CoursesSliceDefaultPrimaryCourseCardsItem {
  /**
   * Image field in *Courses → Default → Primary → Course Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.course_cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Courses → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.course_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Courses → Default → Primary → Course Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.course_cards[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Link field in *Courses → Default → Primary → Course Cards*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.course_cards[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Courses → Default → Primary*
 */
export interface CoursesSliceDefaultPrimary {
  /**
   * Heading field in *Courses → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Course Cards field in *Courses → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: courses.default.primary.course_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  course_cards: prismic.GroupField<
    Simplify<CoursesSliceDefaultPrimaryCourseCardsItem>
  >;
}

/**
 * Default variation for Courses Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoursesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CoursesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Courses*
 */
type CoursesSliceVariation = CoursesSliceDefault;

/**
 * Courses Shared Slice
 *
 * - **API ID**: `courses`
 * - **Description**: Courses
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CoursesSlice = prismic.SharedSlice<
  "courses",
  CoursesSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Link field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Events → Default → Primary → Event Cards*
 */
export interface EventsSliceDefaultPrimaryEventCardsItem {
  /**
   * Event Cards field in *Events → Default → Primary → Event Cards*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.event_cards[].event_cards
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event_cards: prismic.ContentRelationshipField<"event_card">;
}

/**
 * Primary content in *Events → Default → Primary*
 */
export interface EventsSliceDefaultPrimary {
  /**
   * Heading field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Events → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Link field in *Events → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Event Cards field in *Events → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events.default.primary.event_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_cards: prismic.GroupField<
    Simplify<EventsSliceDefaultPrimaryEventCardsItem>
  >;
}

/**
 * Default variation for Events Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Events*
 */
type EventsSliceVariation = EventsSliceDefault;

/**
 * Events Shared Slice
 *
 * - **API ID**: `events`
 * - **Description**: Events
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsSlice = prismic.SharedSlice<"events", EventsSliceVariation>;

/**
 * Item in *EventsBanner → Default → Primary → Card*
 */
export interface EventsBannerSliceDefaultPrimaryCardItem {
  /**
   * Counter field in *EventsBanner → Default → Primary → Card*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.card[].counter
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  counter: prismic.KeyTextField;

  /**
   * Title field in *EventsBanner → Default → Primary → Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.card[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Item in *EventsBanner → Default → Primary → Tag*
 */
export interface EventsBannerSliceDefaultPrimaryTagItem {
  /**
   * Tag Text field in *EventsBanner → Default → Primary → Tag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.tag[].tag_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag_text: prismic.KeyTextField;
}

/**
 * Item in *EventsBanner → Default → Primary → Event Card*
 */
export interface EventsBannerSliceDefaultPrimaryEventCardItem {
  /**
   * Event field in *EventsBanner → Default → Primary → Event Card*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.event_card[].event
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  event: prismic.ContentRelationshipField<"event_card">;
}

/**
 * Primary content in *EventsBanner → Default → Primary*
 */
export interface EventsBannerSliceDefaultPrimary {
  /**
   * Card field in *EventsBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  card: prismic.GroupField<Simplify<EventsBannerSliceDefaultPrimaryCardItem>>;

  /**
   * Tag field in *EventsBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.tag[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  tag: prismic.GroupField<Simplify<EventsBannerSliceDefaultPrimaryTagItem>>;

  /**
   * Event Card field in *EventsBanner → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: events_banner.default.primary.event_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_card: prismic.GroupField<
    Simplify<EventsBannerSliceDefaultPrimaryEventCardItem>
  >;
}

/**
 * Default variation for EventsBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventsBannerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventsBanner*
 */
type EventsBannerSliceVariation = EventsBannerSliceDefault;

/**
 * EventsBanner Shared Slice
 *
 * - **API ID**: `events_banner`
 * - **Description**: EventsBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventsBannerSlice = prismic.SharedSlice<
  "events_banner",
  EventsBannerSliceVariation
>;

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Image field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading field in *Header → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Heading1 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading1
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading1: prismic.RichTextField;

  /**
   * Heading2 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading2
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading2: prismic.RichTextField;

  /**
   * Heading3 field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading3
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading3: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *PartnersAndClients → Default → Primary → Carousel*
 */
export interface PartnersAndClientsSliceDefaultPrimaryCarouselItem {
  /**
   * Partner field in *PartnersAndClients → Default → Primary → Carousel*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_and_clients.default.primary.carousel[].partner
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  partner: prismic.ImageField<never>;
}

/**
 * Primary content in *PartnersAndClients → Default → Primary*
 */
export interface PartnersAndClientsSliceDefaultPrimary {
  /**
   * Heading field in *PartnersAndClients → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_and_clients.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Carousel field in *PartnersAndClients → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners_and_clients.default.primary.carousel[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  carousel: prismic.GroupField<
    Simplify<PartnersAndClientsSliceDefaultPrimaryCarouselItem>
  >;
}

/**
 * Default variation for PartnersAndClients Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersAndClientsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersAndClientsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnersAndClients*
 */
type PartnersAndClientsSliceVariation = PartnersAndClientsSliceDefault;

/**
 * PartnersAndClients Shared Slice
 *
 * - **API ID**: `partners_and_clients`
 * - **Description**: PartnersAndClients
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PartnersAndClientsSlice = prismic.SharedSlice<
  "partners_and_clients",
  PartnersAndClientsSliceVariation
>;

/**
 * Item in *Team → Default → Primary → Team Cards*
 */
export interface TeamSliceDefaultPrimaryTeamCardsItem {
  /**
   * Image field in *Team → Default → Primary → Team Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_cards[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Team → Default → Primary → Team Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_cards[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * Title field in *Team → Default → Primary → Team Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_cards[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Primary content in *Team → Default → Primary*
 */
export interface TeamSliceDefaultPrimary {
  /**
   * Heading field in *Team → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Team Cards field in *Team → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: team.default.primary.team_cards[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  team_cards: prismic.GroupField<
    Simplify<TeamSliceDefaultPrimaryTeamCardsItem>
  >;
}

/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TeamSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Team*
 */
type TeamSliceVariation = TeamSliceDefault;

/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: Team
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TeamSlice = prismic.SharedSlice<"team", TeamSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → Testimonial Card*
 */
export interface TestimonialsSliceDefaultPrimaryTestimonialCardItem {
  /**
   * Testimonial field in *Testimonials → Default → Primary → Testimonial Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_card[].testimonial
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  testimonial: prismic.RichTextField;

  /**
   * Name field in *Testimonials → Default → Primary → Testimonial Card*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_card[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  heading: prismic.RichTextField;

  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Body field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Testimonial Card field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.testimonial_card[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  testimonial_card: prismic.GroupField<
    Simplify<TestimonialsSliceDefaultPrimaryTestimonialCardItem>
  >;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ActivitiesDocument,
      ActivitiesDocumentData,
      ActivitiesDocumentDataSlicesSlice,
      CoursesDocument,
      CoursesDocumentData,
      CoursesDocumentDataSlicesSlice,
      EventCardDocument,
      EventCardDocumentData,
      EventsDocument,
      EventsDocumentData,
      EventsDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataNaviconsItem,
      AllDocumentTypes,
      AboutSlice,
      AboutSliceDefaultPrimary,
      AboutSliceVariation,
      AboutSliceDefault,
      ActivitiesSlice,
      ActivitiesSliceDefaultPrimaryActivitiesCardItem,
      ActivitiesSliceDefaultPrimary,
      ActivitiesSliceVariation,
      ActivitiesSliceDefault,
      ActivitiesBannerSlice,
      ActivitiesBannerSliceDefaultPrimary,
      ActivitiesBannerSliceTrainingPrimary,
      ActivitiesBannerSliceOnlinePrimary,
      ActivitiesBannerSliceVariation,
      ActivitiesBannerSliceDefault,
      ActivitiesBannerSliceTraining,
      ActivitiesBannerSliceOnline,
      ActivityContainerSlice,
      ActivityContainerSliceDefaultPrimaryGalleryItem,
      ActivityContainerSliceDefaultPrimary,
      ActivityContainerSliceVariation,
      ActivityContainerSliceDefault,
      BlogsSlice,
      BlogsSliceDefaultPrimaryBlogCardsItem,
      BlogsSliceDefaultPrimary,
      BlogsSliceVariation,
      BlogsSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      CourseCardsSlice,
      CourseCardsSliceDefaultPrimaryCourseCardsItem,
      CourseCardsSliceDefaultPrimary,
      CourseCardsSliceVariation,
      CourseCardsSliceDefault,
      CoursesSlice,
      CoursesSliceDefaultPrimaryCourseCardsItem,
      CoursesSliceDefaultPrimary,
      CoursesSliceVariation,
      CoursesSliceDefault,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation,
      CtaSliceDefault,
      EventsSlice,
      EventsSliceDefaultPrimaryEventCardsItem,
      EventsSliceDefaultPrimary,
      EventsSliceVariation,
      EventsSliceDefault,
      EventsBannerSlice,
      EventsBannerSliceDefaultPrimaryCardItem,
      EventsBannerSliceDefaultPrimaryTagItem,
      EventsBannerSliceDefaultPrimaryEventCardItem,
      EventsBannerSliceDefaultPrimary,
      EventsBannerSliceVariation,
      EventsBannerSliceDefault,
      HeaderSlice,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PartnersAndClientsSlice,
      PartnersAndClientsSliceDefaultPrimaryCarouselItem,
      PartnersAndClientsSliceDefaultPrimary,
      PartnersAndClientsSliceVariation,
      PartnersAndClientsSliceDefault,
      TeamSlice,
      TeamSliceDefaultPrimaryTeamCardsItem,
      TeamSliceDefaultPrimary,
      TeamSliceVariation,
      TeamSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryTestimonialCardItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
    };
  }
}
