// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  activities: dynamic(() => import("./Activities")),
  blogs: dynamic(() => import("./Blogs")),
  contact: dynamic(() => import("./Contact")),
  courses: dynamic(() => import("./Courses")),
  events: dynamic(() => import("./Events")),
  header: dynamic(() => import("./Header")),
  hero: dynamic(() => import("./Hero")),
  partners_and_clients: dynamic(() => import("./PartnersAndClients")),
  team: dynamic(() => import("./Team")),
  testimonials: dynamic(() => import("./Testimonials")),
};
