// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  courses: dynamic(() => import("./Courses")),
  hero: dynamic(() => import("./Hero")),
};
